### PR TITLE
Fix issue #178, adds form and styling for heroku placeholder

### PR DESCRIPTION
**Pull request by schalkneethling**
@FrancescoSTL r?

### CODE REVIEW

**Comment by chrismore** [comment]
@schalkneethling do we want to have the entire sidebar content in the html of this page that will iframed or just the form content? I was expecting that the sidebar content for the sticker would be in the sidebar and only the form content is in the all-aboard-remote static html file, but it probably doesn't matter. having the entire sidebar content in this HTML gives us full control over the contents of the page. The only issue is that when add ThinkSmart's form to the page, it will be an iframe (sidebar) inside of an iframe (heroku iframe).

**Comment by chrismore** [comment]
What your thoughts on just having the form be the iframe and the rest of the content to be inside the add-on like it exists now? 

This would mean row 17-25 is what is the iframe here:

https://github.com/mozilla/all-aboard/blob/master/data/tmpl/reward.html#L17

**Comment by FrancescoSTL** [comment]
@chrismore @schalkneethling There are some benefits to that, the biggest one being that we can limit the amount of content that is remotely hosted so that the entire sidebar isn't broken if the server is down. We might also want to include the success message within the iframe

**Comment by chrismore** [comment]
same thing for the "offer closed" message when the window of collecting sticker offers is over: https://github.com/mozilla/all-aboard/issues/157

**Comment by schalkneethling** [comment]
> @schalkneethling do we want to have the entire sidebar content in the html of this page that will iframed or just the form content?

I would vote for only the form being remotely hosted, as it is in this PR

**Comment by chrismore** [comment]
@schalkneethling ok, let's go with only the form being remotely hosted. The rest will be local to Firefox.

**Comment by schalkneethling** [comment]
@chrismore Alrighty. Can you merge this (I do not have merge access) and I will get the rest done as soon as I have heard back from @lonnen

**Pull request merged**
